# $Id: Makefile,v 1.1.1.1 2005/06/14 04:38:31 svitak Exp $
#
#	Makefile for netcdf man
#

include ../macros.make

PACKING_LIST	= Makefile	\
		  netcdf.m4

all:

test:

install:

include ../rules.make
